# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:servertun => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.11.150', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn-net"},
                ]
  },
:clienttun => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.11.151', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn-net"},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder "./", "/vagrant"
    config.vm.define boxname do |box|

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
        end

        box.vm.box = boxconfig[:box_name]

        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
          yum install openssh-clients
        SHELL

        case boxname.to_s
        when "servertun"
          config.vm.provision "shell", path: "servertun.sh"
        end

      end

  end

end
