# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.11.150', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn-net"},
                ]
  },
:client => {

        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.11.151', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn-net"},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder "./", "/vagrant"
    config.vm.define boxname do |box|

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
        end

        box.vm.box = boxconfig[:box_name]

        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        case boxname.to_s
        when "server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y epel-release
            yum install -y openvpn iperf3 
            setenforce 0
            mv /vagrant/server.conf /etc/openvpn/server.conf
            mv /vagrant/static.key /etc/openvpn/static.key
            openvpn --config /etc/openvpn/server.conf &
            iperf3 -s &
            SHELL
        when "client"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y epel-release
            yum install -y openvpn iperf3
            setenforce 0
            echo "1"
            mv /vagrant/client.conf /etc/openvpn/client.conf
            echo "11"
            mv /vagrant/static.key /etc/openvpn/static.key
            echo "111"
            openvpn --config /etc/openvpn/client.conf &
            echo "1111"
            iperf3 -c 10.11.12.1 -t 40 -i 5 >> statistic.log
            echo "11111"
            SHELL
        end
      end

  end

end
